### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Sopher** [Sauilitired/IS-Download#11]
**spigot version:**
`[14:22:46 INFO]: This server is running CraftBukkit version git-Spigot-f09662d-0bf75bb (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`

**logs:**
`[14:23:03 ERROR]: Could not load 'plugins/FastAsyncWorldEdit-bukkit-1.13.150.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[server.jar:git-Spigot-f09662d-0bf75bb]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:332) ~[server.jar:git-Spigot-f09662d-0bf75bb]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:252) [server.jar:git-Spigot-f09662d-0bf75bb]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:325) [server.jar:git-Spigot-f09662d-0bf75bb]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [server.jar:git-Spigot-f09662d-0bf75bb]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [server.jar:git-Spigot-f09662d-0bf75bb]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.<clinit>(WorldEditPlugin.java:93) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_171]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:60) ~[server.jar:git-Spigot-f09662d-0bf75bb]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[server.jar:git-Spigot-f09662d-0bf75bb]
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:136) ~[server.jar:git-Spigot-f09662d-0bf75bb]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82) ~[server.jar:git-Spigot-f09662d-0bf75bb]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.<clinit>(WorldEditPlugin.java:93) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_171]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:60) ~[server.jar:git-Spigot-f09662d-0bf75bb]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[server.jar:git-Spigot-f09662d-0bf75bb]
	... 6 more`

**Comment by Citymonstret** [comment]
This is not the place to report FAWE errors. This is the download website repository for the organization.
